// ===== CRICTAKKAR ON THIS DAY =====
// A small bank of dated cricket history events, each verified against ESPNcricinfo
// and/or Wikipedia before being added (Question Quality Rule applies here too, since
// a wrong date is just as bad as a wrong quiz answer). Started with 18 entries spread
// across the calendar — more can be added over time the same way.
//
// month is 1-12, day is 1-31 (calendar day, year is just for display/context —
// matching only checks month+day so the card recurs every year on that date).

const onThisDayEvents = [
  { month: 2, day: 7, year: 1999, title: "Kumble's perfect 10", fact: "🎳 Anil Kumble took 10 wickets for 74 runs against Pakistan at Feroz Shah Kotla, Delhi — only the second bowler in Test history to take all 10 in an innings." },
  { month: 2, day: 24, year: 2010, title: "Sachin's ODI double century", fact: "👑 Sachin Tendulkar scored 200* off 147 balls against South Africa in Gwalior — the first double century in ODI history." },
  { month: 3, day: 15, year: 2001, title: "The Eden Gardens miracle", fact: "🌟 India beat Australia by 171 runs at Eden Gardens after following on — only the third time this had happened in Test history. VVS Laxman's 281 and Rahul Dravid's 180 added 376 runs together." },
  { month: 3, day: 16, year: 2012, title: "Sachin's 100th international century", fact: "🏏 Sachin Tendulkar became the first batsman ever to score 100 international centuries, reaching the landmark against Bangladesh in the 2012 Asia Cup at Mirpur." },
  { month: 4, day: 2, year: 2011, title: "India lift the World Cup at home", fact: "🏆 India beat Sri Lanka by 6 wickets at Wankhede Stadium, Mumbai to win the 2011 Cricket World Cup — becoming the first team ever to win the World Cup on home soil." },
  { month: 4, day: 12, year: 2004, title: "Lara's 400 not out", fact: "🦁 Brian Lara scored an unbeaten 400 against England in Antigua — still the highest individual score in Test cricket history." },
  { month: 4, day: 18, year: 2008, title: "The first ever IPL match", fact: "🏟️ The very first IPL match was played at M Chinnaswamy Stadium, Bengaluru — RCB vs KKR. Brendon McCullum smashed an unbeaten 158 as KKR won by 140 runs." },
  { month: 6, day: 3, year: 2025, title: "RCB's maiden IPL title", fact: "🏆 Royal Challengers Bengaluru won their first ever IPL title, beating Punjab Kings by 6 runs in the final at Narendra Modi Stadium, Ahmedabad." },
  { month: 6, day: 18, year: 1983, title: "Kapil Dev's forgotten masterpiece", fact: "🔥 Kapil Dev scored an unbeaten 175 against Zimbabwe at Tunbridge Wells after India had slipped to 17 for 5 — one of the greatest ODI innings ever, and there's no surviving footage of it." },
  { month: 6, day: 25, year: 1932, title: "India's first ever Test match", fact: "🇬🇧 India played their first ever Test match, against England at Lord's, with CK Nayudu as captain. England won, but Mohammad Nissar's opening burst left them shaken." },
  { month: 6, day: 25, year: 1983, title: "India's first World Cup", fact: "🇮🇳 India beat the mighty West Indies by 43 runs at Lord's to win their first Cricket World Cup — one of the biggest upsets in sport history, under captain Kapil Dev." },
  { month: 7, day: 11, year: 1930, title: "Bradman's 309 in a day", fact: "🐐 Don Bradman scored 309 runs in a single day of Test cricket against England at Headingley, Leeds — a record that still stands nearly a century later." },
  { month: 7, day: 19, year: 1952, title: "Trueman tears into India", fact: "🔥 A 21-year-old Fred Trueman took 8 for 31 in his third-ever Test, as India collapsed to 58 all out against England at Old Trafford — England won by an innings and 207 runs." },
  { month: 7, day: 19, year: 2015, title: "Smith's Lord's double", fact: "🏏 Steve Smith made 215 — the first double-century by an Australian at Lord's since World War II — as Australia thrashed England by 405 runs to level the 2015 Ashes, bowling the hosts out for just 103 in the second innings." },
  { month: 7, day: 20, year: 2017, title: "Harmanpreet's 171*", fact: "💥 Batting through injury with a dislocated finger, Harmanpreet Kaur smashed an unbeaten 171 off 115 balls against defending champions Australia in the 2017 Women's World Cup semi-final at Derby, taking India to their second World Cup final by 36 runs." },
  { month: 7, day: 20, year: 2009, title: "Flintoff's Lord's farewell", fact: "🎯 Andrew Flintoff took a five-wicket haul in his final Test appearance at Lord's, sealing a 115-run win over Australia — England's first Ashes victory at the Home of Cricket in 75 years." },
  { month: 7, day: 21, year: 1981, title: "Botham's Ashes miracle", fact: "🔥 England, forced to follow on at Headingley, somehow beat Australia by 18 runs — Ian Botham's defiant 149 not out set up the chase, and Bob Willis ripped through with 8 for 43. Only the second team in Test history to win after following on." },
  { month: 7, day: 22, year: 2010, title: "Murali's perfect goodbye", fact: "🎯 Muttiah Muralitharan took his 800th Test wicket — Pragyan Ojha, caught behind — off the very last ball he ever bowled in Test cricket, at his farewell Test in Galle. He remains the only bowler in history to reach 800 Test wickets." },
  { month: 7, day: 23, year: 2017, title: "India's heartbreak at Lord's", fact: "😢 A packed Lord's watched England beat India by just 9 runs to win the Women's Cricket World Cup — India lost their last 7 wickets for only 28 runs while chasing 229. Anya Shrubsole's 6 for 46 sealed it, but India's run to the final transformed the profile of women's cricket back home." },
  { month: 7, day: 24, year: 2010, title: "Amir's Headingley heist", fact: "🌟 A 18-year-old Mohammad Amir took 7 wickets in the match to help Pakistan beat Australia at Headingley — their first Test win over Australia in 15 years, after Australia were skittled for just 88." },
  { month: 7, day: 25, year: 2011, title: "The 2000th Test", fact: "💯 Lord's hosted the 2000th Test match ever played — fittingly also the 100th between England and India. Kevin Pietersen's unbeaten 202 anchored England's 474 for 8 declared, and India lost by an innings, denying Sachin Tendulkar a shot at his 100th international century at the Home of Cricket (he'd get there 8 months later, against Bangladesh)." },
  { month: 7, day: 26, year: 1902, title: "Cricket's tightest classic", fact: "😰 Australia beat England by just 3 runs at Old Trafford — one of the closest results in Test history. Victor Trumper had scored a century before lunch on day one, and England's last man, Fred Tate, was out for 4 attempting the winning hit after dropping a crucial catch earlier in the match." },
  { month: 7, day: 27, year: 1990, title: "Gooch's 456-run match", fact: "🐐 Graham Gooch made 333 and 123 against India at Lord's, becoming the first batsman ever to score a triple-century and a century in the same first-class match — his match aggregate of 456 remains a Test record for one batter in a single match." },
  { month: 7, day: 27, year: 2025, title: "Old Trafford rearguard", fact: "🛡️ Washington Sundar scored his maiden Test century, alongside Ravindra Jadeja's hundred, to bat out the final day and save the fourth Test against England at Old Trafford in the inaugural Anderson-Tendulkar Trophy — after England had piled up 669." },
  { month: 7, day: 28, year: 1973, title: "The first ever Cricket World Cup", fact: "🏆 Two years before the men's first World Cup, England beat Australia by 92 runs at Edgbaston to win the inaugural Women's Cricket World Cup — cricket's very first World Cup of any kind. Enid Bakewell's 118 anchored England's winning total." },
  { month: 7, day: 29, year: 2006, title: "The biggest stand of all", fact: "🧱 Mahela Jayawardene (374) and Kumar Sangakkara (287) added 624 for Sri Lanka's third wicket against South Africa in Colombo — still the highest partnership for any wicket in Test cricket history, batting for nearly three days." },
  { month: 7, day: 29, year: 2001, title: "Masakadza's teenage ton", fact: "🌱 At 17 years and 354 days old, Hamilton Masakadza became the youngest player ever to score a century on Test debut, and the first black African Test centurion, making 119 for Zimbabwe against West Indies — a record that lasted barely six weeks before Bangladesh's Mohammad Ashraful broke it." },
  { month: 7, day: 30, year: 1995, title: "Cork's hat-trick", fact: "🎩 Dominic Cork took a hat-trick against West Indies at Old Trafford — the first Test hat-trick by an England bowler since Peter Loader in 1957 — as England went on to win by six wickets." },
  { month: 7, day: 31, year: 1956, title: "Laker's impossible 19", fact: "🎳 Jim Laker took 19 wickets for 90 runs in a single Test at Old Trafford — 9 for 37 in the first innings and all 10 for 53 in the second — still the best match bowling figures in first-class cricket history, over 65 years on." },
  { month: 8, day: 1, year: 1993, title: "England's second Women's World Cup", fact: "🏆 England beat New Zealand by 67 runs at Lord's to win the 1993 Women's Cricket World Cup — their second title, and their first since the inaugural 1973 tournament. Jo Chamberlain was Player of the Match." },
  { month: 8, day: 5, year: 1966, title: "Sobers' Headingley masterclass", fact: "👑 Garry Sobers scored 174 and took match figures of 8 for 80 (5 for 41 plus 3 in the follow-on) against England at Headingley — part of a series in which he made 722 runs at 103.14 and took 20 wickets as West Indies won 3-1." },
  { month: 8, day: 2, year: 2003, title: "Smith's twin double at Lord's", fact: "🏏 Graeme Smith, in only his fourth Test as captain, made 259 at Lord's — following 277 at Edgbaston earlier in the series — still the highest score by a visiting batsman at Lord's, surpassing Don Bradman's 254 from 1930. South Africa won by an innings and 92 runs." },
  { month: 8, day: 3, year: 2000, title: "A joint 100th Test cap", fact: "💯 Mike Atherton and Alec Stewart both played their 100th Test together, against West Indies at Old Trafford — Stewart marked the occasion with 105, becoming only the fourth player in history to score a century in his 100th Test." },
  { month: 8, day: 4, year: 2019, title: "Smith's comeback double at Edgbaston", fact: "🔥 On his first Test back from a one-year ball-tampering ban, Steve Smith scored 144 and 142 at Edgbaston — becoming only the fifth Australian ever to score twin centuries in an Ashes Test — as Australia won by 251 runs." },
  { month: 8, day: 6, year: 2015, title: "Broad blows Australia away at Trent Bridge", fact: "💥 Stuart Broad took 8 for 15 as Australia were bowled out for just 60 in 18.3 overs — the fewest overs a team has faced in a Test innings — helping England win by an innings and 78 runs to regain the Ashes at Trent Bridge." },
  { month: 8, day: 7, year: 1997, title: "Brothers on debut", fact: "👬 Adam and Ben Hollioake became just the third pair of brothers to make their England Test debut in the same match, in the fifth Ashes Test at Trent Bridge. Ben, aged 19 years 269 days, was England's youngest Test player since 1949." },
  { month: 8, day: 7, year: 2005, title: "Edgbaston's 2-run classic", fact: "😱 England beat Australia by 2 runs at Edgbaston — the narrowest margin of victory in Ashes history — after Michael Kasprowicz gloved Steve Harmison behind with Australia just 3 runs short. Andrew Flintoff's all-round performance and sportsmanship toward a devastated Brett Lee became one of cricket's most iconic images." },
  { month: 5, day: 18, year: 1955, title: "The 347-run stand", fact: "🏗️ Denis Atkinson (219) and wicketkeeper Clairmonte Depeiaza (122) added 347 for West Indies' seventh wicket against Australia in Bridgetown — still a Test record for that wicket today. Atkinson also took 5 for 56, becoming the first player to score a century and take a five-for in the same Test." },
  { month: 8, day: 10, year: 1991, title: "Tufnell's Oval spell", fact: "🌀 Phil Tufnell took 6 for 25 as England bowled out West Indies at The Oval to level the series — a career-best haul that came from a devastating mid-innings burst of wickets." },
  { month: 8, day: 11, year: 2005, title: "Warne's 600th", fact: "🎳 Shane Warne became the first bowler in Test history to reach 600 wickets, trapping Marcus Trescothick at Old Trafford during the 2005 Ashes — Adam Gilchrist completing a juggling catch off the leading edge." },
  { month: 8, day: 11, year: 1977, title: "Boycott's 100th, on cue", fact: "💯 Geoffrey Boycott became the first player ever to score his 100th first-class century in a Test match itself, doing it on his home ground at Headingley against Australia — he went on to make 191." },
  { month: 8, day: 12, year: 1972, title: "Brothers in arms", fact: "👬 Ian Chappell made 192 and Greg Chappell also reached three figures in the same Test innings against England at The Oval, the pair adding 201 together — the first pair of brothers ever to both score centuries in the same Test innings." },
  { month: 8, day: 13, year: 1976, title: "Richards' 291", fact: "🔥 Viv Richards made 291 against England at The Oval — his second double-century of the series, having also scored 232 at Trent Bridge earlier in the summer." },
  { month: 8, day: 13, year: 1982, title: "Mohsin Khan's Lord's double", fact: "🏏 Mohsin Khan scored 200 at Lord's, setting up a ten-wicket win for Pakistan — their first Test win in England in 28 years — with opening partner Mudassar Nazar chipping in with 6 for 32 in England's second innings." },
  { month: 8, day: 14, year: 1948, title: "Bradman's final duck", fact: "😢 Don Bradman was bowled for a duck by Eric Hollies in his very last Test innings, at The Oval — needing just 4 runs to retire with a career average of exactly 100, he finished on 99.94 instead, still the greatest batting average in Test history." },
  { month: 8, day: 15, year: 1964, title: "Fiery Fred's 300", fact: "🎯 Fred Trueman became the first bowler in history to take 300 Test wickets at The Oval. Having dismissed Ian Redpath and Garth McKenzie off successive balls, he just missed a hat-trick when Neil Hawke survived the next delivery — only for Hawke himself to become the historic 300th wicket, caught by Colin Cowdrey." },
  { month: 8, day: 16, year: 2000, title: "Cricket goes indoors", fact: "🏟️ Australia beat South Africa by 94 runs at Melbourne's Colonial Stadium in the first ever international cricket match played indoors, under a closed retractable roof." },
  { month: 8, day: 17, year: 1976, title: "Holding's Oval demolition", fact: "💥 Michael Holding took 14 wickets for 149 runs in the match (8 for 92 and 6 for 57) against England at The Oval — still the best match figures ever by a West Indian bowler, on a pitch so flat that every other fast bowler in the match combined took only 5 wickets." },
  { month: 8, day: 17, year: 2002, title: "Mithali Raj's world record 214", fact: "🏏 A 19-year-old Mithali Raj scored 214 against England at Taunton — the highest individual score in women's Test cricket at the time, breaking Karen Rolton's 209*. The record has since been passed by Pakistan's Kiran Baluch (242 in 2004)." },
  { month: 8, day: 18, year: 1934, title: "Ponsford and Bradman's 451", fact: "🧱 Bill Ponsford (266, his last Test innings) and Don Bradman (244) added 451 for Australia's second wicket against England at The Oval — still the highest partnership in Australian Test history." },
  { month: 8, day: 18, year: 2000, title: "The two-day Test", fact: "⚡ England bowled out West Indies for just 61 to win inside two days at Headingley — the first Test finished in two days since 1946 — with Andy Caddick taking four wickets in a single over." },
  { month: 8, day: 19, year: 1953, title: "England regain the Ashes", fact: "🏆 England won the Ashes back at The Oval after a 19-year wait, Tony Lock and Jim Laker sharing nine wickets in Australia's second innings — the first Ashes series won under a professional (not amateur) England captain, Len Hutton." },
  { month: 8, day: 20, year: 2006, title: "The forfeited Test", fact: "😤 Pakistan refused to retake the field after being penalised for ball-tampering at The Oval, and umpires awarded the match to England by forfeit — the first Test in history to end this way, in over 1,000 Tests played to that point." },
  { month: 8, day: 21, year: 1986, title: "Botham's script-writer moment", fact: "🎬 Ian Botham, back from a two-month ban, dismissed New Zealand's Bruce Edgar with the very first ball of his comeback Test at The Oval to equal Dennis Lillee's world record of 355 Test wickets — then went past it in his next over. Team-mate Graham Gooch's reaction summed it up: \"Who writes your scripts?\"" },
  { month: 8, day: 22, year: 1930, title: "Bradman's 974", fact: "🐐 Don Bradman's 232 sealed an innings win for Australia at The Oval and regained the Ashes — capping a series in which he scored 974 runs at 139.14, including three double-centuries, still the record for the most runs in a single Test series nearly a century on." },
  { month: 8, day: 22, year: 2011, title: "England complete the sweep", fact: "🧹 England finished off a 4-0 series whitewash of India at The Oval — Ian Bell's maiden Test double-century (235) built a 350-run stand with Kevin Pietersen, while India's Rahul Dravid carried his bat for an unbeaten 146 in the follow-on." },
  { month: 8, day: 23, year: 1938, title: "Hutton's record 364", fact: "📈 22-year-old Len Hutton passed Don Bradman's Ashes record of 334 on his way to 364 at The Oval — the highest individual Test score at the time — as England declared on 903 for 7, still their highest Test total ever. Bradman, who fractured his ankle while bowling, was the first to congratulate him." },
  { month: 8, day: 24, year: 1971, title: "India's first Test win in England", fact: "🇮🇳 Bhagwath Chandrasekhar took 6 for 38 to bowl England out for just 101 at The Oval, as India won by 4 wickets — their first-ever Test victory on English soil, ending England's 26-Test unbeaten run." },
  { month: 8, day: 24, year: 1972, title: "The first ODI century", fact: "💯 Dennis Amiss scored 103 for England against Australia at Old Trafford — the first century ever made in One Day International cricket." },
  { month: 8, day: 25, year: 2019, title: "Stokes' Headingley miracle", fact: "🤯 Chasing 359 and reduced to 286 for 9, Ben Stokes carried England home with an unbeaten 135, adding 76 for the last wicket with Jack Leach (1 not out) — England's highest-ever successful Test run chase, keeping the 2019 Ashes alive with a one-wicket win." },
  { month: 8, day: 27, year: 1968, title: "The Oval's rain-soaked thriller", fact: "🌧️ England beat Australia by 226 runs at The Oval to level the series, after spectators helped mop up a lunchtime storm so play could resume — Derek Underwood took 7 for 50 with just minutes to spare. Basil D'Oliveira's 158 in the match fueled the political storm that followed when he was later left out of the tour to South Africa." },
  { month: 8, day: 27, year: 1973, title: "Sobers' last hurrah at Lord's", fact: "🙌 On what turned out to be his last tour of England, Garry Sobers made the 26th and final Test century of his career at Lord's, and held six catches in the match to equal the then-record for catches by a non-wicketkeeper in a Test." },
  { month: 8, day: 28, year: 1992, title: "A wizard's quiet beginning", fact: "🎩 Muttiah Muralitharan made his Test debut against Australia in Colombo, taking 3 for 141 — Craig McDermott his first wicket. Nobody could have guessed it was the start of a career that would end with 800 Test wickets, still the most by anyone in history." },
  { month: 8, day: 26, year: 1920, title: "The 35-minute century", fact: "⚡ Percy Fender scored a century in just 35 minutes for Surrey against Northamptonshire — still the fastest century by time in first-class cricket history, over a century later." },
  { month: 8, day: 26, year: 1963, title: "Worrell's final bow", fact: "🙏 Frank Worrell led West Indies to an eight-wicket win over England at The Oval in his final Test, sealing a 3-1 series victory — he was the first black cricketer to captain West Indies for an entire series, and the two nations now play for the Frank Worrell Trophy." },
  { month: 8, day: 29, year: 1882, title: "The birth of the Ashes", fact: "☠️ Australia beat England by 7 runs at The Oval — England's first-ever home Test defeat — as Fred Spofforth took 14 wickets in the match. The Sporting Times ran a mock obituary for English cricket, joking its ashes would be sent to Australia, and the name stuck forever." },
  { month: 9, day: 19, year: 2007, title: "Yuvraj's six sixes", fact: "💥 Yuvraj Singh hit Stuart Broad for six sixes in a single over during the 2007 T20 World Cup in Durban — the first player to do it in international T20 cricket." },
  { month: 9, day: 24, year: 2007, title: "India's first T20 World Cup", fact: "🏆 MS Dhoni's young India side beat Pakistan by 5 runs in Johannesburg to win the inaugural ICC T20 World Cup, with Joginder Sharma bowling the final over." },
  { month: 9, day: 12, year: 2005, title: "Pietersen seals the urn", fact: "🏆 Kevin Pietersen's series-defining 158 helped England hold on for a draw at The Oval, sealing a 2-1 series win and reclaiming the Ashes for the first time since 1986-87 after Australia's 16-year, eight-series stranglehold on the urn." },
  { month: 9, day: 30, year: 2002, title: "Cricket's only shared world trophy", fact: "🤝 Rain twice washed out the ICC Champions Trophy final between India and Sri Lanka at the R. Premadasa Stadium, Colombo — after two separate attempts on 29 and 30 September both ended in downpours, the tournament trophy was shared, the only time this has happened in a global ICC event." },
  { month: 10, day: 5, year: 2023, title: "Ravindra's stunning World Cup bow", fact: "🌟 In his first-ever World Cup match, New Zealand's Rachin Ravindra made 123 not out and put on an unbeaten 273 with Devon Conway as New Zealand chased down defending champions England's 282 by 9 wickets in the tournament opener at Ahmedabad." },
  { month: 10, day: 5, year: 2009, title: "Watson's Champions Trophy repeat", fact: "🏆 Shane Watson's unbeaten 105 carried Australia to a 6-wicket win over New Zealand in the final at Centurion — successfully defending their 2006 title and earning Watson the Player of the Match award in a Champions Trophy final for the second tournament running." },
  { month: 10, day: 24, year: 2021, title: "Pakistan finally beat India at a World Cup", fact: "💚 Mohammad Rizwan and Babar Azam's unbeaten opening stand carried Pakistan to a 10-wicket win over India in Dubai — Pakistan's first-ever win over India at any men's World Cup, in any format, after 13 previous meetings." },
  { month: 11, day: 13, year: 2014, title: "Rohit's 264", fact: "💥 Rohit Sharma scored 264 against Sri Lanka at Eden Gardens, Kolkata — still the highest individual score in ODI history." },
  { month: 11, day: 14, year: 2013, title: "Sachin's final Test begins", fact: "🙏 Sachin Tendulkar walked out for his 200th and final Test, against West Indies at Wankhede Stadium — the closing chapter of a 24-year international career." },
  { month: 11, day: 15, year: 1989, title: "Sachin's international debut", fact: "🇮🇳 A 16-year-old Sachin Tendulkar made his Test debut against Pakistan in Karachi — the start of a career that would redefine Indian cricket." },
  { month: 11, day: 19, year: 2023, title: "Australia's sixth World Cup", fact: "🏆 Australia beat host nation India in the 2023 ODI World Cup final at Narendra Modi Stadium, Ahmedabad, to win a record sixth World Cup title." },
  { month: 11, day: 27, year: 2014, title: "The death of Phillip Hughes", fact: "🖤 Australian batsman Phillip Hughes died two days after being struck on the neck by a bouncer while batting for South Australia against New South Wales at the SCG — his death led directly to mandatory neck-guard standards on cricket helmets worldwide." },
  { month: 11, day: 29, year: 2015, title: "Cricket's first day-night Test", fact: "💡 Australia beat New Zealand by 3 wickets at the Adelaide Oval in the first ever day-night Test match, played with a pink ball under floodlights — a record crowd of 123,736 watched across the three days." },
  { month: 12, day: 2, year: 1932, title: "Bodyline's quiet beginning", fact: "😤 England beat Australia by 10 wickets in the first Test of the infamous Bodyline series at Sydney — Harold Larwood took 10 wickets in the match, and it was here that journalist Hugh Buggy first coined the term 'bodyline' to describe England's leg-theory bowling." },
  { month: 12, day: 19, year: 2020, title: "India's lowest-ever Test total", fact: "📉 India were bowled out for just 36 in their second innings against Australia in Adelaide — their lowest total in Test history, with Josh Hazlewood taking 5 for 8 in a pink-ball day-night Test." },
  { month: 12, day: 23, year: 2012, title: "Sachin bids farewell to ODIs", fact: "🙏 Sachin Tendulkar announced his retirement from One Day Internationals, bringing the curtain down on a career of 463 ODIs, 18,426 runs and 49 centuries — all of them world records at the time." },
  { month: 8, day: 14, year: 1984, title: "West Indies complete the Blackwash", fact: "⚫ West Indies beat England by 172 runs at The Oval to complete a 5-0 series sweep — the first time a touring side had ever blackwashed a five-Test series in England." },
  { month: 8, day: 14, year: 1990, title: "Sachin's maiden Test century", fact: "🎯 A 17-year-old Sachin Tendulkar scored an unbeaten 119 to save the second Test against England at Old Trafford — his first Test century, batting through most of the final day to force a draw." },
  { month: 8, day: 30, year: 2016, title: "England's world-record 444", fact: "🔥 England smashed 444 for 3 against Pakistan at Trent Bridge — then the highest total in ODI history — with Alex Hales blazing 171 off 122 balls, an England record individual ODI score at the time. England won by 169 runs." },
  { month: 8, day: 31, year: 1968, title: "Six sixes in an over", fact: "💥 Garry Sobers became the first batsman ever to hit six sixes in a single six-ball over in first-class cricket, off Malcolm Nash of Glamorgan at Swansea — the sixth was a mis-hit that fielder Roger Davis caught but carried over the boundary rope, so the umpire signalled it a six anyway." },
  { month: 8, day: 31, year: 1769, title: "Cricket's first century", fact: "💯 John Minshull scored 107 for the Duke of Dorset's XI against Wrotham at Sevenoaks Vine — the earliest century definitively recorded in the history of cricket, decades before Test cricket even existed." },
  { month: 9, day: 3, year: 2024, title: "Bangladesh's historic series win in Pakistan", fact: "🐯 Bangladesh completed a stunning 2-0 Test series sweep of Pakistan — their first-ever series win there in 13 previous meetings — chasing down 185 in Rawalpindi after collapsing to 26 for 6 in the first innings, with Litton Das and Mehidy Hasan Miraz's 165-run stand sparking the fightback." },
  { month: 9, day: 6, year: 1880, title: "The first Test century in England", fact: "🏏 WG Grace scored 152 on debut in the first-ever Test match played on English soil, at The Oval — England won by 5 wickets. Two of his brothers also played in the match." },
  { month: 9, day: 6, year: 2016, title: "Maxwell's 263", fact: "💥 Glenn Maxwell smashed an unbeaten 145 off 65 balls as Australia posted 263 for 3 against Sri Lanka in Pallekele — then the highest team total in T20I history, beating Sri Lanka's own previous record of 260." },
  { month: 9, day: 6, year: 2021, title: "India's first Oval win since 1971", fact: "🏏 India beat England by 157 runs at The Oval to win the 4th Test of the series — Rohit Sharma's 127 was his first century outside Asia, and it was India's first Test victory at the venue since 1971." },
  { month: 9, day: 8, year: 2001, title: "Ashraful's teenage record", fact: "🌟 A 17-year-old Mohammad Ashraful scored 114 on Test debut against Sri Lanka in Colombo, becoming the youngest centurion in Test history at 17 years and 63 days." },
  { month: 9, day: 8, year: 2019, title: "Australia seal the Ashes", fact: "🇦🇺 Steve Smith's 211 and 82 — his third Ashes double-century — powered Australia to a 185-run win over England at Old Trafford, retaining the Ashes on English soil for the first time since 2001." },
  { month: 9, day: 9, year: 1994, title: "Sachin's first ODI century", fact: "💯 Sachin Tendulkar scored 110 against Australia in Colombo — his first century in One Day International cricket, in a Singer World Series match, on the way to becoming the format's all-time leading century-maker." },
  { month: 9, day: 11, year: 1985, title: "Sri Lanka's first Test win", fact: "🇱🇰 Sri Lanka beat India by 149 runs in Colombo for their first ever Test victory, coming in just their 14th Test. Wicketkeeper-opener Amal Silva was Player of the Match for a century plus nine dismissals." },
  { month: 9, day: 11, year: 2007, title: "T20 cricket's first century", fact: "💥 Chris Gayle smashed 117 off 57 balls for West Indies against South Africa at the Wanderers — the first-ever century in T20 International cricket — in the opening match of the inaugural ICC World Twenty20. South Africa still won by 8 wickets." },
  { month: 9, day: 13, year: 1969, title: "The birth of a leg-spin legend", fact: "🎩 Shane Warne was born in Melbourne — he would go on to take 708 Test wickets, revive leg-spin as a match-winning art, and become one of Wisden's Five Cricketers of the 20th Century." },
  { month: 9, day: 14, year: 1957, title: "Wessels' unusual double", fact: "🇿🇦 Kepler Wessels was born in South Africa — he scored 162 on Test debut for Australia against England in 1982, then years later captained South Africa and scored 105 against England at Lord's in 1994, becoming South Africa's first century-maker at that ground in 39 years." },
  { month: 9, day: 14, year: 2007, title: "Cricket's only bowl-out", fact: "🎯 India and Pakistan tied their T20 World Cup group match in Durban, so the result was decided by a bowl-out — five players a side aiming at bare stumps with no batter defending them. India won it 3-0." },
  { month: 9, day: 22, year: 1986, title: "The second Tied Test", fact: "🤝 Dean Jones battled dehydration and repeated vomiting to score 210 in Chennai's heat, chasing a target of 348 — but the Test between Australia and India still ended in a tie after Greg Matthews had Maninder Singh out lbw off the penultimate ball, only the second time it had happened in over a century of Test cricket." },
  { month: 9, day: 22, year: 2007, title: "India oust Australia", fact: "🇮🇳 Yuvraj Singh's 70 off 30 balls carried India to a 15-run win over Australia in Durban, sending MS Dhoni's side into the final of the inaugural T20 World Cup." },
  { month: 10, day: 4, year: 2018, title: "Prithvi Shaw's dream debut", fact: "🌟 18-year-old Prithvi Shaw became the youngest Indian to score a century on Test debut, making 134 off 154 balls against West Indies at Rajkot — just 18 years and 329 days old." },
  { month: 10, day: 7, year: 2012, title: "West Indies' first World T20", fact: "🏆 Marlon Samuels' 78 and Sunil Narine's 3 for 9 gave West Indies a 36-run win over hosts Sri Lanka in Colombo, handing them their maiden World Twenty20 title." },
  { month: 10, day: 11, year: 2000, title: "Cronje banned for life", fact: "⚫ South Africa's former captain Hansie Cronje was banned from all cricket for life by the United Cricket Board of South Africa, after admitting to the King Commission that he had accepted money from bookmakers to fix matches." },
  { month: 10, day: 22, year: 1992, title: "Zimbabwe's first Test", fact: "🇿🇼 Zimbabwe played their inaugural Test match, against India in Harare, with captain David Houghton scoring the country's first-ever Test century (121) as the match ended in a draw." },
  { month: 10, day: 30, year: 2016, title: "Bangladesh's first Test win over England", fact: "🐯 Bangladesh beat England by 108 runs in Mirpur to record their first-ever Test win over a full-strength major team, sharing the series 1-1 — 19-year-old debutant offspinner Mehidy Hasan Miraz took 19 wickets across the two Tests, the most ever by a Bangladeshi bowler in a series." },
  { month: 10, day: 31, year: 2005, title: "Dhoni's wicketkeeper world record", fact: "🚁 MS Dhoni smashed an unbeaten 183 off 145 balls against Sri Lanka in Jaipur, with 10 sixes — still the highest individual score by a wicketkeeper in ODI history." },
  { month: 11, day: 1, year: 1998, title: "The first Champions Trophy", fact: "🏆 South Africa beat West Indies by 4 wickets in Dhaka to win the inaugural ICC KnockOut Trophy — the tournament later renamed the Champions Trophy, and still South Africa's only global ICC title. Jacques Kallis took 5 for 30 to help peg back Philo Wallace's 103, before Hansie Cronje's unbeaten 61 sealed the chase." },
  { month: 11, day: 2, year: 2008, title: "Kumble's Delhi farewell", fact: "🎽 Anil Kumble announced his retirement at the end of the Delhi Test against Australia, finishing his career with 619 Test wickets — at the time the third-most in Test history, behind only Muralitharan and Warne." },
  { month: 11, day: 2, year: 2013, title: "Rohit's sixathon", fact: "🎆 Rohit Sharma smashed 209 off 158 balls against Australia in Bangalore — only the third double-century in ODI history, after Tendulkar (2010) and Sehwag (2011) — hitting a then-world-record 16 sixes in the innings, a mark later broken by Eoin Morgan's 17 (2019)." },
  { month: 11, day: 2, year: 2025, title: "India Women's maiden World Cup", fact: "🏆 India Women beat South Africa by 52 runs at DY Patil Stadium to win their first ever ICC Women's Cricket World Cup. Shafali Verma's 87 won her Player of the Match, and Deepti Sharma's five-wicket haul plus a fifty made her Player of the Tournament." },
  { month: 11, day: 7, year: 2023, title: "Maxwell's impossible double century", fact: "🤯 Glenn Maxwell scored an unbeaten 201 off 128 balls to chase down a target of 292 against Afghanistan at the World Cup — battling severe cramps throughout, it's the first double century by a non-opening batter in ODI history." },
  { month: 11, day: 8, year: 1987, title: "Australia's first World Cup", fact: "🏆 Australia won their first-ever Cricket World Cup, beating England by 7 runs in the final at Eden Gardens, Calcutta — David Boon's 75 anchored Australia's 253/5 and won him Player of the Match, as England fell just short on 246/8." },
  { month: 11, day: 10, year: 1991, title: "South Africa return from isolation", fact: "🕊️ South Africa played their first One Day International in over 20 years, against India at Eden Gardens — their readmission to world cricket ending decades of apartheid-era isolation." },
  { month: 11, day: 10, year: 2008, title: "Ganguly's first-ball farewell", fact: "👋 Sourav Ganguly played his last Test innings at Nagpur, out for a golden duck off the very first ball he faced — India still won the match, and the series, by 172 runs against Australia." },
  { month: 11, day: 22, year: 2019, title: "India's first day-night Test", fact: "🌗 India played their first ever day-night Test, using a pink ball under lights against Bangladesh at Eden Gardens, Kolkata." },
  { month: 11, day: 30, year: 1928, title: "The Don's quiet start", fact: "😅 A 20-year-old Don Bradman made an underwhelming Test debut, scoring just 18 and 1 as England thrashed Australia by 675 runs at the Brisbane Exhibition Ground — still the biggest winning margin by runs in Test history. He was dropped for the next Test, but never looked back after that." },
  { month: 12, day: 2, year: 1977, title: "World Series Cricket's first Supertest", fact: "💰 Kerry Packer's breakaway World Series Cricket staged its first 'Supertest' — Australia against West Indies at VFL Park, Melbourne — as the biggest names in the game defected from official cricket for two revolutionary seasons." },
  { month: 12, day: 4, year: 2021, title: "The third-ever perfect 10", fact: "🎳 New Zealand's Ajaz Patel took all 10 wickets in an innings against India at the Wankhede Stadium, Mumbai — only the third bowler in Test history to do it, after Jim Laker and Anil Kumble, and the first ever to achieve it away from home." },
  { month: 12, day: 18, year: 1989, title: "Sachin's ODI debut", fact: "🇮🇳 A 16-year-old Sachin Tendulkar made his ODI debut against Pakistan at Gujranwala — out for a two-ball duck, caught off Waqar Younis, in a match India lost by 7 runs." },
  { month: 12, day: 30, year: 2014, title: "Dhoni's Test retirement", fact: "🙏 MS Dhoni announced his retirement from Test cricket with immediate effect, moments after India's drawn Boxing Day Test against Australia in Melbourne — handing the captaincy to Virat Kohli for the final Test of the series in Sydney." },
  { month: 1, day: 3, year: 2016, title: "Stokes' Cape Town blitz", fact: "🔥 Ben Stokes smashed 258 off 198 balls against South Africa at Cape Town, reaching his double-century in just 163 balls — the second-fastest in Test history — as he and Jonny Bairstow added a world-record 399 for England's sixth wicket." },
  { month: 1, day: 14, year: 1933, title: "The Bodyline flashpoint", fact: "😤 Australia captain Bill Woodfull was struck over the heart by a Harold Larwood bouncer during the Adelaide Test — England captain Douglas Jardine's shout of 'Well bowled, Harold!' turned the Bodyline series into a full-blown diplomatic incident." },
  { month: 1, day: 15, year: 1988, title: "Hirwani's dream debut", fact: "🎯 On Test debut, legspinner Narendra Hirwani took 16 wickets for 136 runs against West Indies in Chennai — still the best match figures by any bowler on Test debut in history, beating Bob Massie's 16 for 137 from 1972." },
  { month: 1, day: 18, year: 2015, title: "AB's 31-ball century", fact: "⚡ AB de Villiers smashed the fastest century in ODI history, reaching three figures off just 31 balls against West Indies in Johannesburg, on his way to 149 not out off 44 balls — still the standing world record." },
  { month: 1, day: 29, year: 1998, title: "The Sabina Park Test", fact: "😰 The first Test between West Indies and England at Sabina Park was abandoned after just 10.1 overs when the pitch proved too dangerous to play on — one of only a handful of Tests in history called off due to an unfit ground." },
  { month: 1, day: 30, year: 1993, title: "Ambrose's 7 for 1", fact: "🎳 Curtly Ambrose took 7 wickets for just 1 run in a devastating spell at the WACA, Perth, ripping through Australia from 85 for 2 to 119 all out in the deciding Test — one of the greatest bowling spells in cricket history." },
  { month: 2, day: 8, year: 1994, title: "Kapil Dev's 432nd wicket", fact: "🎈 Kapil Dev became the leading wicket-taker in Test history, claiming his 432nd wicket — Sri Lanka's Hashan Tillakaratne — to pass Richard Hadlee's record at Ahmedabad. The stadium released 432 balloons to mark the occasion." },
  { month: 2, day: 11, year: 1984, title: "The first tied ODI", fact: "🤝 Australia and West Indies played out the first-ever tied ODI, in the second final of the World Series Cup at the MCG — both sides finishing on 222, with Carl Rackemann run out attempting the winning run." },
  { month: 4, day: 1, year: 2004, title: "The Sultan of Multan", fact: "🏏 Virender Sehwag smashed 309 at Multan — India's first-ever Test triple-century — powering them to 675/5 declared and an innings-and-52-run win, India's first-ever Test victory on Pakistani soil. They went on to win the series 2-1, their first Test series win in Pakistan too." },
  { month: 4, day: 3, year: 2016, title: "Brathwaite's four sixes in a row", fact: "💥 Carlos Brathwaite smashed four consecutive sixes off Ben Stokes in the final over to seal West Indies' second men's T20 World Cup title, beating England by 4 wickets at Eden Gardens, Kolkata." },
  { month: 4, day: 3, year: 2022, title: "Healy's record-breaking final", fact: "🏏 Alyssa Healy smashed 170 — still the highest individual score in any Cricket World Cup final, men's or women's — as Australia beat England by 71 runs at Hagley Oval, Christchurch to win their 7th Women's Cricket World Cup title." },
  { month: 4, day: 6, year: 2014, title: "Sri Lanka's maiden T20 crown", fact: "🏆 Kumar Sangakkara's unbeaten 52 guided Sri Lanka to a 6-wicket win over India at Sher-e-Bangla, Mirpur, finally winning the T20 World Cup after two runner-up finishes — and marking the last T20I of both Sangakkara's and Mahela Jayawardene's careers." },
  { month: 4, day: 7, year: 2000, title: "The match-fixing scandal breaks", fact: "🚨 Delhi Police publicly implicated South Africa captain Hansie Cronje in fixing ODIs against India, releasing phone-tap transcripts with an alleged bookmaker — the moment that blew cricket's match-fixing scandal wide open." },
  { month: 4, day: 10, year: 2005, title: "India's first Women's World Cup final", fact: "🏏 Karen Rolton's 107 helped Australia beat India by 98 runs at Centurion to win their 5th Women's Cricket World Cup — India's first-ever appearance in a Women's World Cup final." },
  { month: 4, day: 11, year: 2000, title: "Cronje's 3am confession", fact: "📞 Four days after denying everything at a press conference, Hansie Cronje called South African cricket chief Ali Bacher at 3am and admitted he had 'not been entirely honest' — he was stripped of the captaincy within hours." },
  { month: 4, day: 15, year: 1986, title: "Master blasting", fact: "💥 Viv Richards smashed an unbeaten 110 off just 58 balls against England at St John's, Antigua — the fastest century in Test history by balls faced at the time, a record that stood for 30 years until Brendon McCullum's 54-ball century in 2016." },
  { month: 4, day: 22, year: 1998, title: "Desert Storm, part one", fact: "🌪️ Batting through a swirling sandstorm at Sharjah, Sachin Tendulkar's 143 against Australia kept India alive on net run rate to reach the final — an innings later voted by ICC fans (2020) as his greatest ODI knock." },
  { month: 4, day: 23, year: 2013, title: "Gayle-force at Chinnaswamy", fact: "💣 Chris Gayle smashed 175* off 66 balls for RCB against Pune Warriors India — still the highest individual score in T20 history, though his 30-ball century and 17-six tally have both since been bettered in other T20 innings." },
  { month: 4, day: 24, year: 1998, title: "Desert Storm, part two", fact: "🎂 Two days after his sandstorm masterclass, and on his 25th birthday, Sachin Tendulkar blazed 134 in the final to beat Australia and win the Coca-Cola Cup — India's revenge completed in the same tournament." },
  { month: 4, day: 28, year: 2007, title: "Australia's World Cup three-peat", fact: "🏆 Adam Gilchrist's 149 off 104 balls powered Australia to a 53-run (D/L) win over Sri Lanka at Kensington Oval, Barbados, in a chaotic near-darkness final — their third consecutive Cricket World Cup title." },
  { month: 5, day: 4, year: 1990, title: "Akram's second ODI hat-trick", fact: "🎩 Wasim Akram bowled Merv Hughes, Carl Rackemann and Terry Alderman with three consecutive deliveries to seal the Austral-Asia Cup final in Sharjah, snapping Australia's 10-match winning streak — his second career ODI hat-trick." },
  { month: 5, day: 11, year: 2018, title: "Ireland's historic Test debut", fact: "🇮🇪 Ireland became the 11th nation to play Test cricket, taking on Pakistan at Malahide — a Test in which Kevin O'Brien became Ireland's first-ever Test centurion, with 118." },
  { month: 5, day: 13, year: 2003, title: "The greatest run-chase", fact: "🔥 Chasing an unprecedented 418 to win, West Indies pulled off Test cricket's greatest run-chase in Antigua — Ramnaresh Sarwan's 105 and an injured Shivnarine Chanderpaul's defiant 104 (batting with a broken finger) carried them home by three wickets, still the highest successful fourth-innings chase in Test history." },
  { month: 5, day: 14, year: 2022, title: "The loss of a Baggy Green great", fact: "🖤 Australian allrounder Andrew Symonds died in a car accident near Townsville, Queensland, aged 46 — a huge loss felt across the cricket world he'd entertained for over a decade." },
  { month: 5, day: 15, year: 2017, title: "Deepti-Raut's world-record stand", fact: "🏏 Deepti Sharma (188) and Poonam Raut (109) put on an unbeaten 320 for India's first wicket against Ireland in Potchefstroom — the highest partnership in Women's ODI history, and at the time the highest opening stand in ODI cricket by either gender." },
  { month: 5, day: 16, year: 2010, title: "England's first world title", fact: "🏆 England beat Australia by 7 wickets at Kensington Oval, Barbados to win the 2010 ICC World Twenty20 — captain Paul Collingwood became the first England skipper to lift a global men's ICC trophy." },
  { month: 5, day: 16, year: 2013, title: "The IPL's darkest night", fact: "⚫ Delhi Police arrested Rajasthan Royals trio S Sreesanth, Ankeet Chavan and Ajit Chandila for spot-fixing during IPL 2013 — the scandal that first exposed match manipulation inside the tournament." },
  { month: 5, day: 16, year: 1953, title: "Bowled out twice in a day", fact: "😳 Surrey bowled out Warwickshire for 45 and 52 in the same day at The Oval to win by an innings — Alec Bedser took 8 for 18 and 4 for 17, with ten Warwickshire batters out for a duck across the match." },
  { month: 5, day: 17, year: 2009, title: "Yuvraj's second act", fact: "🎩 Yuvraj Singh took 3 for 13, including a hat-trick, to help Kings XI Punjab beat Deccan Chargers by 1 run in Johannesburg — his second hat-trick of that IPL season, having also taken one against RCB two weeks earlier." },
  { month: 5, day: 18, year: 1905, title: "The birth of a spin wizard", fact: "🎳 Hedley Verity was born in Leeds — he'd go on to take 10 wickets for just 10 runs against Nottinghamshire at Headingley in 1932, including a hat-trick, still the most economical 10-wicket haul in first-class cricket history." },
  { month: 5, day: 19, year: 1874, title: "The fastest century of the Golden Age", fact: "⚡ Gilbert Jessop was born — nicknamed 'The Croucher', he remains one of the fastest run-scorers in cricket history, famous for a legendary 104 in 77 minutes against Australia at The Oval in 1902 that turned a hopeless 48 for 5 into a stunning one-wicket win for England." },
  { month: 5, day: 20, year: 1943, title: "The vice-captain who stole a thriller", fact: "🤝 Deryck Murray was born — West Indies' wicketkeeper and vice-captain of their 1975 World Cup-winning side, best remembered for an unbroken last-wicket stand of 64 with Andy Roberts that stole a one-wicket win over Pakistan in the very first World Cup, at Edgbaston in 1975." },
  { month: 5, day: 20, year: 1911, title: "Alletson's furious 189", fact: "⚡ Nottinghamshire's Ted Alletson smashed 189 in around 90 minutes against Sussex at Hove — including 34 runs off a single over — one of the most explosive innings in first-class cricket history, and the only century of his career." },
  { month: 5, day: 21, year: 1997, title: "Anwar's then-record 194", fact: "💥 Saeed Anwar blazed 194 off 146 balls against India in Chennai — the highest individual score in ODI history at the time, a record that stood until Fakhar Zaman's 210* in 2018." },
  { month: 5, day: 22, year: 1907, title: "Trott's double hat-trick", fact: "🎩 In his own benefit match at Lord's, Albert Trott took two separate hat-tricks in the same innings for Middlesex against Somerset, finishing with 7 for 20 — a feat matched only once since, by Joginder Rao in 1963-64." },
  { month: 5, day: 22, year: 1879, title: "The Big Ship who never lost an Ashes", fact: "🚢 Warwick Armstrong — nicknamed 'The Big Ship' — was born. He captained Australia to cricket's first-ever Ashes whitewash, 5-0 in 1920-21 (not repeated until Ricky Ponting's side matched it in 2006-07), and still holds the record for most consecutive Ashes wins as captain, 8." },
  { month: 5, day: 23, year: 2025, title: "Forde's 16-ball fifty", fact: "🔥 West Indies' Matthew Forde smashed a fifty off just 16 balls against Ireland in Dublin, equalling AB de Villiers' record for the fastest fifty in ODI history, on his way to 58 off 19 balls." },
  { month: 5, day: 23, year: 1918, title: "Compo is born", fact: "🏏 Denis Compton was born — in the sun-drenched summer of 1947 he'd score 3,816 first-class runs including 18 centuries in a single season, both still-standing world records unlikely ever to be broken given how few matches are played today." },
  { month: 5, day: 24, year: 1942, title: "Poacher-turned-gamekeeper", fact: "🇿🇦 Ali Bacher was born — he captained South Africa to a 4-0 whitewash of Australia in 1969-70, their last series before 22 years of apartheid-era isolation, then later helped broker South Africa's return to international cricket in 1991 as the country's top administrator." },
  { month: 5, day: 25, year: 1995, title: "The paceman who broke South Africa's title drought", fact: "⚡ Kagiso Rabada was born — in the 2025 World Test Championship final at Lord's he took 5 for 51 in the first innings as South Africa beat Australia to win their first ICC title in 27 years." },
  { month: 5, day: 26, year: 1999, title: "Ganguly-Dravid's Taunton rampage", fact: "🚀 Sourav Ganguly (183) and Rahul Dravid (145) put on 318 for India's second wicket against Sri Lanka at Taunton in the 1999 World Cup — the highest partnership in ODI history at the time." },
  { month: 5, day: 26, year: 2024, title: "Narine's double impact", fact: "🏆 Kolkata Knight Riders beat Sunrisers Hyderabad by 8 wickets in Chennai to win their 3rd IPL title — Sunil Narine was named Player of the Series after contributing 488 runs and 17 wickets across the tournament, a rare true all-round campaign." },
  { month: 5, day: 27, year: 2012, title: "KKR's maiden IPL crown", fact: "🏆 Kolkata Knight Riders chased down 191 with two balls to spare to beat Chennai Super Kings by 5 wickets in their home final at Chennai — Manvinder Bisla's 89 off 48 balls sealed KKR's first-ever IPL title." },
  { month: 5, day: 27, year: 1977, title: "The best of the right-handers", fact: "🏏 Mahela Jayawardene was born — his 374 against South Africa at the SSC in 2006 remains the highest Test score ever by a right-handed batsman, and was part of a world-record 624-run stand with Kumar Sangakkara." },
  { month: 5, day: 28, year: 1912, title: "Matthews' unique double", fact: "🎯 Australia's Jimmy Matthews took a hat-trick in South Africa's first innings and another in their second — both on the same day at Old Trafford — still the only instance of two hat-tricks in one Test match, over a century later." },
  { month: 5, day: 28, year: 1934, title: "Hobbs' last hurrah", fact: "🏏 Jack Hobbs, aged 51 years and 163 days, scored his final first-class century — for Surrey against Lancashire at Old Trafford — one of the most remarkable displays of longevity in cricket history." },
  { month: 5, day: 28, year: 1974, title: "Pakistan's crisis man", fact: "🧊 Misbah-ul-Haq was born — famous for ice-cool finishes, he equaled Viv Richards' record for the fastest Test century (56 balls) in 2014, and later captained Pakistan to the 2012 Asia Cup title, beating Bangladesh by 2 runs." },
  { month: 5, day: 29, year: 2023, title: "CSK's fifth title", fact: "🏆 Ravindra Jadeja smashed the last two balls of a rain-delayed final for six and four to seal Chennai Super Kings' win over Gujarat Titans — their 5th IPL title, drawing level with Mumbai Indians as joint-most successful franchise." },
  { month: 5, day: 30, year: 2016, title: "Cook's record-breaking landmark", fact: "📈 Alastair Cook became the first Englishman to reach 10,000 Test runs, getting there against Sri Lanka at Chester-le-Street — at 31 years old, he beat Sachin Tendulkar's previous youngest-to-the-mark record by about five months." },
  { month: 5, day: 30, year: 1895, title: "The Indian summer of WG Grace", fact: "🎩 W.G. Grace completed 1,000 first-class runs in the month of May alone — the first batsman ever to do it, at 46 years old. The same purple patch included his 100th century, an innings of 288 against Somerset." },
  { month: 5, day: 30, year: 1902, title: "36 all out at Edgbaston", fact: "😬 Australia were bowled out for just 36 in 90 minutes by England at Edgbaston — Wilfred Rhodes taking 7 for 17 — with Victor Trumper's unbeaten 18 accounting for half the total. Rain then washed out the final day, saving Australia from defeat in the drawn Test." },
  { month: 5, day: 31, year: 1984, title: "Richards' greatest ODI innings", fact: "👑 Viv Richards blasted an unbeaten 189 off 170 balls against England at Old Trafford, rescuing his side from 166/9 with a last-wicket stand of 106 with Michael Holding — rated by the ICC as the greatest ODI innings ever played." },
  { month: 5, day: 31, year: 2026, title: "RCB defend their crown", fact: "🏆 Royal Challengers Bengaluru beat Gujarat Titans by 5 wickets in Ahmedabad to defend their IPL title — only the third franchise ever to win back-to-back titles, after Chennai Super Kings and Mumbai Indians. Virat Kohli struck his fastest-ever IPL fifty in the final." },
  { month: 6, day: 1, year: 2002, title: "Cronje's tragic end", fact: "✈️ Hansie Cronje, the disgraced former South Africa captain banned for life over match-fixing, died in a plane crash in the Outeniqua Mountains near George — just two years after his fall from grace, aged 32." },
  { month: 6, day: 1, year: 1899, title: "The Champion's farewell", fact: "🎩 W.G. Grace, aged 50, played the last of his 22 Tests for England, against Australia at Trent Bridge — he stood down as captain afterwards, admitting his fielding had suffered because 'the ground was getting a bit too far away.'" },
  { month: 6, day: 1, year: 2024, title: "T20 World Cup's American debut", fact: "🇺🇸 The first-ever ICC Men's T20 World Cup match played on US soil: co-hosts USA beat Canada by 7 wickets at Grand Prairie Stadium, Dallas, in the tournament opener, with Aaron Jones scoring an unbeaten 94." },
  { month: 6, day: 2, year: 1965, title: "The catching twin", fact: "🧤 Mark Waugh was born in Sydney — minutes after his twin brother Steve. One of the finest slip fielders ever, he retired with a then-world-record 181 Test catches by a non-wicketkeeper, a mark later broken by Rahul Dravid and then Joe Root." },
  { month: 6, day: 4, year: 1971, title: "Zaheer Abbas' Edgbaston 274", fact: "🏏 In only his second Test, a 23-year-old Zaheer Abbas made a majestic 274 against England at Edgbaston, powering Pakistan to 608/7 declared — announcing himself as one of the game's great batsmen." },
  { month: 6, day: 4, year: 1993, title: "The Ball of the Century", fact: "🎳 Shane Warne's very first Ashes delivery — a huge leg-break that spun past Mike Gatting's bat to clip off stump at Old Trafford — instantly became known as the 'Ball of the Century'. Warne took match figures of 8/137 and was named Player of the Match." },
  { month: 6, day: 4, year: 1991, title: "England's modern great all-rounder", fact: "🏏 Ben Stokes was born — the hero of England's 2019 World Cup final and 2022 T20 World Cup wins, and Headingley heroics in the 2019 Ashes, he retired from international cricket on 29 June 2026 after 15 years and a four-year spell as Test captain." },
  { month: 6, day: 5, year: 2009, title: "Netherlands' World T20 shock", fact: "🇳🇱 The Netherlands stunned hosts England by 4 wickets on the opening day of the World Twenty20 at Lord's, getting home off the very last ball — one of the great tournament-opening upsets." },
  { month: 6, day: 6, year: 1994, title: "Lara's 501 not out", fact: "📖 Brian Lara rewrote the record books, making 501 not out for Warwickshire against Durham at Edgbaston — still the highest individual score in first-class cricket history, breaking Hanif Mohammad's 499 which had stood for over 35 years." },
  { month: 6, day: 6, year: 2024, title: "USA's Super Over shock", fact: "😱 USA tied with Pakistan on 159 then won a Super Over at the T20 World Cup in Dallas — the USA's first-ever win over Pakistan in T20Is, and one of the biggest upsets in the tournament's history." },
  { month: 6, day: 7, year: 1975, title: "The first-ever World Cup match", fact: "🏆 Cricket's first-ever World Cup got underway at Lord's — England beat India by 202 runs, with Dennis Amiss's 137 one of the first centuries in World Cup history." },
  { month: 6, day: 7, year: 1952, title: "Trueman's explosive Test debut", fact: "😱 On Test debut, 21-year-old Fred Trueman ripped through India's second innings at Headingley — India slumping to 0 for 4 without a run on the board, one of the most sensational collapse starts in Test history." },
  { month: 6, day: 8, year: 2019, title: "Shakib's Cardiff century", fact: "💯 Shakib Al Hasan struck 121 off 119 balls against England at Cardiff in the 2019 World Cup — the start of a tournament in which he passed fifty in seven of his eight innings, the best individual campaign of his career." },
  { month: 6, day: 8, year: 2018, title: "New Zealand's world record 491", fact: "🏏 New Zealand Women smashed 491 for 4 against Ireland in Dublin — the highest total in ODI history, men's or women's, at the time. Suzie Bates (151) and Maddy Green (121) both scored centuries, and 17-year-old Amelia Kerr chipped in an unbeaten 81, as New Zealand won by 347 runs." },
  { month: 6, day: 8, year: 2026, title: "India's biggest Test win", fact: "🌟 Debutant Manav Suthar took 6 for 33 and scored 28 to power India to an innings-and-300-run win over Afghanistan in New Chandigarh — India's biggest margin of victory in Test history, and just the fifth Indian bowler ever to take a five-wicket haul on Test debut." },
  { month: 6, day: 9, year: 1983, title: "Zimbabwe's World Cup shocker", fact: "😲 On their World Cup debut, Zimbabwe stunned Australia by 13 runs at Trent Bridge — Duncan Fletcher's all-round masterclass of 69* and 4/42 sealed one of the tournament's great upsets." },
  { month: 6, day: 9, year: 2024, title: "India edge Pakistan in New York", fact: "🇮🇳 In a low-scoring thriller at the Nassau County stadium in New York, India held off Pakistan by 6 runs at the T20 World Cup." },
  { month: 6, day: 9, year: 2017, title: "Rashid's record spell", fact: "🎯 Rashid Khan took 7 for 18 for Afghanistan against West Indies in St Lucia — the first Associate-nation bowler ever to take 7 wickets in an ODI, as Afghanistan defended 212 to win by 63 runs." },
  { month: 6, day: 10, year: 1986, title: "India conquer HQ", fact: "🏆 India beat England by 5 wickets at Lord's — their first-ever Test win there, sealing a 2-0 series lead. Dilip Vengsarkar's unbeaten 126 was Man of the Match, his third successive Test century at Lord's (1979, 1982, 1986) — still the only non-English batsman to achieve that." },
  { month: 6, day: 10, year: 2018, title: "Scotland's famous six-run shock", fact: "🏴 Scotland beat England — the world's No.1-ranked ODI side — by 6 runs in Edinburgh, their first-ever ODI win over England. Calum MacLeod's unbeaten 140 was the highest score by an Associate nation batsman against a Full Member team." },
  { month: 6, day: 10, year: 1983, title: "The upset that started it all", fact: "😲 India stunned two-time defending champions West Indies by 34 runs at Old Trafford in their opening match of the 1983 World Cup — the Windies' first-ever defeat in the tournament's history. Yashpal Sharma's 89 anchored India's total, and Roger Binny and Ravi Shastri took 3 wickets each." },
  { month: 6, day: 11, year: 2023, title: "Australia's first World Test Championship", fact: "🏆 Travis Head's 163 powered Australia to a 209-run win over India at The Oval, winning the 2023 World Test Championship final — Australia's first WTC title." },
  { month: 6, day: 12, year: 1957, title: "The Karachi streetfighter", fact: "🥊 Javed Miandad was born in Karachi — regarded as Pakistan's greatest-ever batsman, he's only the second player after Herbert Sutcliffe to finish a career of more than seven Tests with his average never dropping below 50, across 124 Tests over 17 years." },
  { month: 6, day: 13, year: 2003, title: "Twenty20's very first match", fact: "🆕 Hampshire beat Sussex by 5 runs in front of a sell-out crowd at the Rose Bowl, Southampton — one of five simultaneous matches on the opening day of English domestic cricket's brand new Twenty20 Cup, and the most famous of them." },
  { month: 6, day: 13, year: 2005, title: "England's first T20I", fact: "🏏 England played their first-ever Twenty20 International, beating Australia by 100 runs at the Rose Bowl, Southampton — bowling Australia out for just 79 after posting 179/8. Kevin Pietersen was Player of the Match." },
  { month: 6, day: 14, year: 2018, title: "Afghanistan's first Test begins", fact: "🇦🇫 Afghanistan played their first-ever Test match, taking on India at the M Chinnaswamy Stadium, Bengaluru — becoming the 12th side to play men's Test cricket, less than a year after being granted Test status." },
  { month: 6, day: 16, year: 2019, title: "Rohit tames Pakistan at Old Trafford", fact: "💥 Rohit Sharma's 140 powered India to a DLS-method 89-run World Cup win over Pakistan at Old Trafford, extending India's unbeaten record against Pakistan across all men's World Cups." },
  { month: 6, day: 17, year: 1999, title: "Cricket's most famous tie", fact: "😱 Australia and South Africa tied their World Cup semi-final at Edgbaston after Allan Donald was run out attempting the winning single — Australia went through on their Super Six standing, in what's widely called the greatest ODI ever played." },
  { month: 6, day: 19, year: 2018, title: "England's world-record 481", fact: "🏏 England smashed 481/6 against Australia at Trent Bridge — the first team ever to cross 450 in an ODI innings, built on twin centuries from Jonny Bairstow (139) and Alex Hales (147). Australia were bowled out for 239, England's biggest ODI win by runs at the time (England later broke their own 481 record with 498/4 vs Netherlands in 2022)." },
  { month: 6, day: 20, year: 1999, title: "Warne's World Cup final masterclass", fact: "🎯 Australia beat Pakistan by 8 wickets at Lord's to win the 1999 World Cup — Shane Warne took 4/33 to bowl out Pakistan for just 132 in the most one-sided final in the tournament's history to that point." },
  { month: 6, day: 21, year: 1975, title: "West Indies' maiden World Cup", fact: "🏆 West Indies beat Australia by 17 runs at Lord's to win the first-ever Cricket World Cup — captain Clive Lloyd's 102 was the only ODI century of his career, rescuing his side from a precarious 50/3." },
  { month: 6, day: 21, year: 2009, title: "Pakistan's maiden T20 crown", fact: "🏆 Pakistan beat Sri Lanka by 8 wickets at Lord's to win the 2009 World Twenty20 — their only T20 World Cup title — with Shahid Afridi's unbeaten 54 earning him the Player of the Match award." },
  { month: 6, day: 22, year: 1983, title: "India book their maiden final", fact: "🏏 India beat England by 6 wickets at Old Trafford and West Indies beat Pakistan by 8 wickets at The Oval on the same day — setting up the 1983 World Cup final between India and two-time champions West Indies three days later." },
  { month: 6, day: 23, year: 1979, title: "West Indies retain the World Cup", fact: "🏆 West Indies beat England by 92 runs at Lord's to win their second straight World Cup — Viv Richards' unbeaten 138 and a 139-run stand with Collis King set up Joel Garner's decisive five-wicket haul." },
  { month: 6, day: 23, year: 2013, title: "India's rain-hit Champions Trophy", fact: "🏆 India beat England by 5 runs in a rain-shortened, 20-overs-a-side Champions Trophy final at Edgbaston — MS Dhoni became the first captain to win the T20 World Cup, ODI World Cup and Champions Trophy." },
  { month: 6, day: 23, year: 2021, title: "New Zealand's inaugural WTC title", fact: "🏆 New Zealand beat India by 8 wickets on the reserve day at Southampton to win the first-ever World Test Championship final — Kane Williamson and Ross Taylor's unbroken stand of 96 sealed the chase." },
  { month: 6, day: 24, year: 1974, title: "India's all-time Test low", fact: "😬 Following on at Lord's, India were bowled out for just 42 in a little over an hour — England's Chris Old (5/21) and Geoff Arnold (4/19) ran through the order. It remains India's lowest-ever Test total, and the lowest by any side at Lord's." },
  { month: 6, day: 26, year: 2024, title: "Afghanistan's record T20I low", fact: "😲 South Africa bowled out Afghanistan for just 56 — their lowest-ever T20I score — then chased it down in 8.5 overs to win their World Cup semi-final by 9 wickets and reach their first-ever men's ICC final." },
  { month: 6, day: 26, year: 2026, title: "Ireland's historic first win over India", fact: "🇮🇪 Captain Lorcan Tucker's half-century paved the way as Ireland beat India by 34 runs in Belfast — Ireland's first-ever win over India in any format, after eight previous attempts." },
  { month: 6, day: 27, year: 2024, title: "Axar's semi-final masterclass", fact: "🎯 Axar Patel took 3/23 as India beat England by 68 runs at Providence Stadium, Guyana to reach the T20 World Cup final — Rohit Sharma (57) and Suryakumar Yadav (47) had set up the total after England were shot out for 103." },
  { month: 6, day: 29, year: 2024, title: "Kohli's farewell masterclass", fact: "🏆 Virat Kohli's attritional 76 anchored India to 176/7 in the T20 World Cup final against South Africa in Barbados — India held on to win by 7 runs and end an 11-year wait for an ICC men's title, in what Kohli announced was his last-ever T20I." },
  { month: 7, day: 1, year: 2000, title: "Cork's Lord's classic", fact: "🏏 England beat West Indies by 2 wickets at Lord's to win the 100th Test ever played there — chasing just 188, they slumped to 160 for 8 before Dominic Cork, who'd already taken 7 for 52 in the match, smashed the winning runs. It was the first Test won inside two days since 1946." },
  { month: 7, day: 2, year: 1969, title: "Ireland's famous 25 all out", fact: "😲 A touring West Indies side was skittled for just 25 by Ireland at Sion Mills — captain Dougie Goodwin took 5/6 as Ireland won on first-innings lead in one of the most famous shock results in cricket history." },
  { month: 7, day: 2, year: 2023, title: "The Bairstow-Carey stumping", fact: "🔥 On the final day of the Lord's Ashes Test, Alex Carey stumped Jonny Bairstow after he wandered out of his crease thinking the ball was dead — a legal but hugely controversial dismissal that overshadowed Australia's 43-run win." },
  { month: 7, day: 2, year: 1935, title: "South Africa's first win in England", fact: "🇿🇦 South Africa beat England by 157 runs at Lord's — their maiden Test victory on English soil. Bruce Mitchell's unbeaten 164 and legspinner Xen Balaskas's 9 wickets in the match did the damage." },
  { month: 7, day: 4, year: 1986, title: "Gatting's captaincy statement", fact: "🏏 In just his second Test in charge, Mike Gatting made an unbeaten 183 as England drew the third Test against India at Edgbaston — a much-needed high point after England had lost seven Tests in a row going into it." },
  { month: 7, day: 4, year: 1984, title: "Kallicharran's double ton and 6-for", fact: "🎩 Alvin Kallicharran smashed 206 then took 6 for 32 with his gentle offspin as Warwickshire thumped Oxfordshire in the NatWest Trophy — the first double-century ever scored in one-day cricket in England." },
  { month: 7, day: 6, year: 2025, title: "India's first Edgbaston win", fact: "🇮🇳 India completed a 336-run win over England at Edgbaston — their first-ever Test victory at the ground after losing seven of their previous eight games there. Shubman Gill's twin centuries (269 and 161) and Akash Deep's ten-wicket match haul, deputising for the injured Jasprit Bumrah, set up a world-record target of 608." },
  { month: 7, day: 7, year: 2005, title: "Cricket's first Super Sub", fact: "🔄 Vikram Solanki became the first player used as an ODI 'Super Sub,' replacing bowler Simon Jones for England against Australia in the NatWest Series at Headingley, and made an unbeaten 53 batting at No. 8." },
  { month: 7, day: 8, year: 1995, title: "West Indies' Edgbaston demolition", fact: "💥 West Indies bowled out England for a shambolic 147 and 89 to win the Edgbaston Test by an innings and 64 runs — England's lowest-ever score at the ground, with Sherwin Campbell's 79 earning Player of the Match." },
  { month: 7, day: 8, year: 1961, title: "Trueman's Match", fact: "🎳 Fred Trueman ripped through Australia in the third Ashes Test at Headingley, finishing with 11 wickets in the match as Australia were bowled out for just 120 in the second innings — England won by 8 wickets to level the series 1-1." },
  { month: 7, day: 9, year: 1965, title: "Edrich's boundary blitz", fact: "🔥 John Edrich made an unbeaten 310 against New Zealand at Headingley, striking 52 fours and 5 sixes — still the most runs scored in boundaries in a single Test innings, as England won by an innings and 187 runs." },
  { month: 7, day: 10, year: 1990, title: "Hadlee's Test farewell", fact: "👋 Sir Richard Hadlee took a wicket with the last ball of his Test career — trapping Devon Malcolm lbw to finish with 5/53 at Edgbaston — as he bowed out with the Man of the Series award at age 39." },
  { month: 7, day: 10, year: 2017, title: "Raza inspires a series win", fact: "🇿🇼 Zimbabwe won the deciding 5th ODI in Hambantota to take the series 3-2 over Sri Lanka — Sikandar Raza took 3 for 21 to restrict the hosts, then anchored the chase himself to seal a famous series win." },
  { month: 7, day: 12, year: 2014, title: "Root and Anderson's Test record", fact: "🤝 James Anderson and Joe Root added an unbeaten, Test-record 198 runs for the tenth wicket against India at Trent Bridge, hauling England from a precarious 298/9 to a position of safety." },
  { month: 7, day: 13, year: 2002, title: "India's NatWest final heist", fact: "👕 Chasing 326 to beat England in the NatWest Series final at Lord's, India got home with 3 balls to spare thanks to Mohammad Kaif's unbeaten 87 — sparking Sourav Ganguly's iconic shirt-swinging celebration on the Lord's balcony." },
  { month: 7, day: 14, year: 2019, title: "Cricket's greatest final", fact: "🏆 The 2019 World Cup final between England and New Zealand at Lord's finished tied after 50 overs each, then tied again after a Super Over — England won their first-ever World Cup on a boundary-count rule, with Ben Stokes unbeaten on 84." },
  { month: 7, day: 15, year: 1938, title: "Fagg's twin double-centuries", fact: "🎯 Kent's Arthur Fagg became the first player in history to score two double-centuries in the same first-class match, making 244 and then 202 not out against Essex at Colchester — a feat repeated by only one other player since, Angelo Perera in 2019." },
  { month: 9, day: 17, year: 2023, title: "Siraj's Asia Cup demolition", fact: "🎳 Mohammed Siraj tore through Sri Lanka with 6/21, including 4 wickets in a single over, as they were bowled out for 50 — the lowest total in any men's ODI final — in the Asia Cup final in Colombo. India completed the chase in just 6.1 overs to win by 10 wickets." },
  { month: 9, day: 20, year: 2020, title: "IPL 2020's Super Over opener", fact: "🏏 IPL 2020's second-ever match ended in a tie — Delhi Capitals and Kings XI Punjab both finished on 157/8 in Dubai, Marcus Stoinis's 53 the difference-maker — before Kagiso Rabada defended the Super Over to open Delhi's UAE campaign with a thriller." },
  { month: 9, day: 23, year: 2018, title: "Rohit and Dhawan's record stand vs Pakistan", fact: "💥 Rohit Sharma (111*) and Shikhar Dhawan (114) put on 210 for India's first wicket while chasing Pakistan's 237 in the Asia Cup Super Four at Dubai — India's best-ever opening stand against Pakistan in ODIs. India won by 9 wickets." },
  { month: 9, day: 26, year: 1844, title: "Cricket's first-ever international match", fact: "🌎 Canada beat the United States by 23 runs at St George's Cricket Club in New York, across a match that ran from 24 to 26 September — widely regarded as the first international match in the history of any modern sport, more than three decades before the first Test. An estimated 20,000 spectators watched." },
  { month: 9, day: 27, year: 2024, title: "Kamindu draws level with the Don", fact: "🎯 In just his 13th Test innings, Sri Lanka's Kamindu Mendis reached 1,000 Test runs during an unbeaten 182 against New Zealand in Galle — matching Don Bradman's exact pace to the milestone and becoming only the third player in Test history, after Herbert Sutcliffe and Everton Weekes, to get there faster." },
  { month: 10, day: 9, year: 1987, title: "The one-run heartbreaker", fact: "💔 Australia beat India by a single run at Chepauk in the 1987 World Cup — Steve Waugh bowled Maninder Singh off the second-last ball to deny India a chase of 270, in the narrowest victory in ODI World Cup history." },
  { month: 11, day: 26, year: 1984, title: "Kim Hughes' tearful resignation", fact: "😢 Australia captain Kim Hughes broke down in tears reading his resignation statement at a Brisbane press conference, stepping down after West Indies completed their 10th consecutive Test victory — one of cricket's most emotionally raw captaincy exits, with Allan Border taking over for the next Test." },
  { month: 12, day: 8, year: 1987, title: "Fury in Faisalabad", fact: "🔥 England captain Mike Gatting and umpire Shakoor Rana erupted into a finger-jabbing shouting match over a fielding-position dispute during the Faisalabad Test — a full day's play was lost until Gatting issued a written apology, in one of cricket's most infamous confrontations." },
  { month: 12, day: 8, year: 2011, title: "Sehwag's second double", fact: "💥 Virender Sehwag blitzed 219 off 149 balls against West Indies at Indore, becoming only the second man to a double-century in ODIs — less than two years after Sachin Tendulkar became the first. India posted 418/5, their highest-ever ODI total, and won by 153 runs." },
  { month: 12, day: 27, year: 1981, title: "Lillee's world record", fact: "🏆 Dennis Lillee had Larry Gomes edge behind on day two of the Boxing Day Test at the MCG — his 310th Test wicket, passing West Indian spinner Lance Gibbs' world record of 309. Lillee went on to finish with 355 Test wickets from just 70 matches." }
];

// ===== PICK AND RENDER TODAY'S CARD =====
function renderOnThisDay() {
  var container = document.getElementById('onThisDayContent');
  if (!container) return;

  var today = new Date();
  var month = today.getMonth() + 1;
  var day = today.getDate();

  var MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  var todayReadable = day + ' ' + MONTH_NAMES[month - 1];

  var matches = onThisDayEvents.filter(function(e) { return e.month === month && e.day === day; });

  if (matches.length > 0) {
    // If more than one event shares a date, rotate deterministically by day-of-year
    // (same pattern Wordle uses) so it's consistent for everyone, but not always the first.
    var dayNumber = Math.floor(today.getTime() / (1000 * 60 * 60 * 24));
    var event = matches[dayNumber % matches.length];

    container.innerHTML =
      '<div class="otd-card">' +
        '<div class="otd-eyebrow">📅 On This Day, ' + todayReadable + ' — ' + event.year + '</div>' +
        '<div class="otd-title">' + event.title + '</div>' +
        '<p class="otd-fact">' + event.fact + '</p>' +
      '</div>';
    return;
  }

  // No historical event logged for today yet — fall back to a "Did You Know" fact
  // from the already-verified daily quiz question bank, rotating daily like Wordle does.
  // Still names today's date so it's clear this card is part of On This Day, not a
  // separate unrelated feature.
  if (typeof questionBank !== 'undefined' && questionBank.length > 0) {
    var dayNumber2 = Math.floor(today.getTime() / (1000 * 60 * 60 * 24));
    var q = questionBank[dayNumber2 % questionBank.length];

    container.innerHTML =
      '<div class="otd-subtext">No cricket event logged for ' + todayReadable + ' yet — here\'s a fact instead:</div>' +
      '<div class="otd-card">' +
        '<div class="otd-eyebrow">💡 Did You Know</div>' +
        '<p class="otd-fact">' + q.fact + '</p>' +
      '</div>';
  } else {
    container.style.display = 'none';
  }
}

document.addEventListener('DOMContentLoaded', renderOnThisDay);
